name: Lingua play Sydney
description: Школа русского языка на северных пляжах Сиднея
google_analytics:
theme:
sass:
  sass_dir: _sass
  style: compressed
collections:
  pages:
    output: true
    permalink: /:name
plugins:
-  jekyll-paginate
-  jekyll-sass-converter
