name: Lingua play Sydney
google_analytics:
theme:
sass:
  sass_dir: _sass
  style: compressed
collections:
  pages:
    output: true
plugins:
  jekyll-sitemap
  jekyll-seo-tag
  jekyll-paginate
  jekyll-sass-converter
